export const SONGS = [
  {
    brand: 'kumyoung',
    no: '82776',
    title: '사랑, 사랑',
    singer: 'Kid Wine         ',
    composer: 'Kid Wine,PATEKO..',
    lyricist: 'Kid Wine         ',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82775',
    title: '묘해, 너와',
    singer: '태일(NCT)',
    composer: '심현보   ',
    lyricist: '심현보   ',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82774',
    title: '멈춰 줘 (드라마"눈물의 여왕")',
    singer: '헤이즈       ',
    composer: '남혜승,박진호',
    lyricist: '남혜승,박진호',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82773',
    title: '꽃이 피는 데 필요한 몇 가지',
    singer: 'NuNew,폴킴       ',
    composer: 'Acharya Dulyapa..',
    lyricist: '폴킴             ',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82765',
    title: '수성의 하루',
    singer: '쏜애플(Thornapple)',
    composer: '윤성현,심재현,방..',
    lyricist: '윤성현            ',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82764',
    title: "라망 (L'amant)",
    singer: '아이유',
    composer: '정재형',
    lyricist: '정재형',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82763',
    title: '고장 난 걸까 (드라마"눈물의 여왕")',
    singer: '10cm         ',
    composer: '남혜승,김경희',
    lyricist: '남혜승,김경희',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82753',
    title: '사랑, 결코 시들지 않는',
    singer: '최영관(신바람 최박..',
    composer: '박세준              ',
    lyricist: '이영준              ',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82752',
    title: '비상',
    singer: '이승기       ',
    composer: '최준영,임재범',
    lyricist: '채정은       ',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82751',
    title: '봄이 와도',
    singer: '로이킴',
    composer: '로이킴',
    lyricist: '로이킴',
    release: '2024-05-01',
  },
  {
    brand: 'kumyoung',
    no: '82750',
    title: '별',
    singer: 'CRAVITY           ',
    composer: '별들의전쟁1,별들..',
    lyricist: '별들의전쟁1,별들..',
    release: '2024-05-01',
  },
];
